### ISSUE TITLE
Odd "0000-00-00 00:00:00" in SimpleStatistics lead to odd x axis

### ISSUE THREAD

**Issue by femtotrader** [mhallsmoore/qstrader#116]
![capture d ecran 2016-07-31 a 17 19 35](https://cloud.githubusercontent.com/assets/5049737/17277446/2314c508-5743-11e6-9a1d-9c9e7e4d1dd0.png)

we can see 0000-00-00 00:00:00 on x-axis... this is quite weird

it might be first event (`BarEvent` or `TickEvent`) time.

https://github.com/mhallsmoore/qstrader/blob/master/qstrader/statistics/simple.py should be fixed

**Comment by ryankennedyio** [comment]
Guess I should fix that :)

Will have a PR for it tonight.

**Comment by femtotrader** [comment]
According https://travis-ci.org/mhallsmoore/qstrader/jobs/149162325
you shouldn't merge this until test doesn't pass

it's not a PEP8 problem
but

```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/mhallsmoore/qstrader/tests/test_statistics.py", line 159, in test_calculating_statistics
    results = statistics.get_results()
  File "/home/travis/build/mhallsmoore/qstrader/qstrader/statistics/simple.py", line 70, in get_results
    timeseries[0] = timeseries[1] - pd.Timedelta(days=1)
  File "pandas/tslib.pyx", line 2522, in pandas.tslib.Timedelta._binary_op_method_timedeltalike.f (pandas/tslib.c:45617)
  File "pandas/tslib.pyx", line 2258, in pandas.tslib.Timedelta.__new__ (pandas/tslib.c:40892)
  File "pandas/tslib.pyx", line 2742, in pandas.tslib.parse_timedelta_string (pandas/tslib.c:48473)
ValueError: only leading negative signs are allowed
```
