### ISSUE TITLE
Build is failling

### ISSUE THREAD

**Issue by femtotrader** [mhallsmoore/qstrader#124]
Just a reminder

Build is failling
because of https://github.com/mhallsmoore/qstrader/pull/121

see https://github.com/mhallsmoore/qstrader/issues/116

According https://travis-ci.org/mhallsmoore/qstrader/jobs/149162325
you shouldn't merge this until test doesn't pass

it's not a PEP8 problem
but

```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/mhallsmoore/qstrader/tests/test_statistics.py", line 159, in test_calculating_statistics
    results = statistics.get_results()
  File "/home/travis/build/mhallsmoore/qstrader/qstrader/statistics/simple.py", line 70, in get_results
    timeseries[0] = timeseries[1] - pd.Timedelta(days=1)
  File "pandas/tslib.pyx", line 2522, in pandas.tslib.Timedelta._binary_op_method_timedeltalike.f (pandas/tslib.c:45617)
  File "pandas/tslib.pyx", line 2258, in pandas.tslib.Timedelta.__new__ (pandas/tslib.c:40892)
  File "pandas/tslib.pyx", line 2742, in pandas.tslib.parse_timedelta_string (pandas/tslib.c:48473)
ValueError: only leading negative signs are allowed
```

**Comment by ryankennedyio** [comment]
Solved in https://github.com/mhallsmoore/qstrader/pull/126

**Comment by femtotrader** [comment]
Just a comment:

It better to add 

Closes https://github.com/mhallsmoore/qstrader/issues/124

in PR as it automatically closes issue when PR is merged
