### ISSUE TITLE
I run the example--MONTHLY REBALANCING OF ETFS WITH FIXED INITIAL WEIGHTS IN QSTRADER

### ISSUE THREAD

**Issue by easytrader** [mhallsmoore/qstrader#146]
I run the example--MONTHLY REBALANCING OF ETFS WITH FIXED INITIAL WEIGHTS IN QSTRADER.
But I meet a problem below:

Traceback (most recent call last):
  File "monthly_liquidate_rebalance.py", line 92, in <module>
    main()
  File "/home/leo/anaconda2/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/leo/anaconda2/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/leo/anaconda2/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/leo/anaconda2/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "monthly_liquidate_rebalance.py", line 88, in main
    run(config, testing, tickers, filename)
  File "monthly_liquidate_rebalance.py", line 75, in run
    results = backtest.simulate_trading(testing=testing)
  File "/home/leo/anaconda2/lib/python2.7/site-packages/qstrader/trading_session/backtest.py", line 76, in simulate_trading
    self.statistics.plot_results()
  File "/home/leo/anaconda2/lib/python2.7/site-packages/qstrader/statistics/tearsheet.py", line 506, in plot_results
    sns.set_context(rc)
  File "/home/leo/anaconda2/lib/python2.7/site-packages/seaborn/rcmod.py", line 440, in set_context
    mpl.rcParams.update(context_object)
  File "/home/leo/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py", line 890, in update
    self[k] = v
  File "/home/leo/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py", line 869, in __setitem__
    See rcParams.keys() for a list of valid parameters.' % (key,))
KeyError: u'figure.titlesize is not a valid rc parameter.See rcParams.keys() for a list of valid parameters.'

**Comment by mhallsmoore** [comment]
Hi easytrader,

This might be due to the version of matplotlib that comes bundled with your version of Anaconda.

Can you open up a terminal and type this for me:

```import matplotlib as mpl
print mpl.__version__```

This will let me know what version you're using and whether you might need to upgrade.

Mike.

**Comment by easytrader** [comment]
Hi mhallsmoore,

This is my computer's shsowing:
>>> import matplotlib as mpl
>>> print mpl.__version__
1.4.3

Thanks

**Comment by mhallsmoore** [comment]
I think the best thing to try first, in order to keep a clean build, is to download the latest version of Anaconda with Python 2.7. Alternatively, you can try Anaconda with Python 3.

I'm hoping that will fix the problem, otherwise I'll try digging into the code in the Tearsheet. Unfortunately, it currently works on mine, although I am using Python 3.4.x for my local dev environment!

**Comment by nwillemse** [comment]
It's working for me @easytrader . I'm using version 1.5.3

```
In [1]: import matplotlib
In [2]: matplotlib.__version__
Out[2]: '1.5.3'
```

@mhallsmoore we need to add matplotlib to the `requirements.txt` file. I forgot to check it.

**Comment by mhallsmoore** [comment]
Ok, I'll add it in.

**Comment by mhallsmoore** [comment]
Hi @nwillemse and @easytrader,

I've just merged in the requirements to use matplotlib==1.5.3 into the requirements file. 

@easytrader - you'll need to type this into your terminal:

```pip install --upgrade matplotlib==1.5.3```

Let me know if you still have trouble with the tearsheet afterwards.

Cheers,

Mike.

**Comment by easytrader** [comment]
Hi mhallsmoore,

pip install --upgrade matplotlib==1.5.3
fix my problem.
Thank you very much.

**Comment by mhallsmoore** [comment]
Great! I'll close the issue.
