### ISSUE TITLE
Hitting import error with tkinter

### ISSUE THREAD

**Issue by moonlight16** [mhallsmoore/qstrader#150]
Out of the box installation of QSTrader on CentOS7 with python3.5.2 breaks here:

(qstraderp3) [root@server examples]# python buy_and_hold_backtest.py
Traceback (most recent call last):
  File "buy_and_hold_backtest.py", line 14, in <module>
    from qstrader.statistics.simple import SimpleStatistics
  File "/root/venv/qstraderp3/lib/python3.5/site-packages/qstrader/statistics/simple.py", line 9, in <module>
    import matplotlib.pyplot as plt
  File "/root/venv/qstraderp3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/root/venv/qstraderp3/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/root/venv/qstraderp3/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from matplotlib.externals.six.moves import tkinter as Tk
  File "/root/venv/qstraderp3/lib/python3.5/site-packages/matplotlib/externals/six.py", line 90, in __get__
    result = self._resolve()
  File "/root/venv/qstraderp3/lib/python3.5/site-packages/matplotlib/externals/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/root/venv/qstraderp3/lib/python3.5/site-packages/matplotlib/externals/six.py", line 80, in _import_module
    __import__(name)
ImportError: No module named 'tkinter'

**Comment by jacohn16** [comment]
Solution:
yum install python35u-tkinter

**Comment by jacohn16** [comment]
I wonder if there's a way to have this installed when installing QSTrader in setup.py?
