### ISSUE TITLE
Setup tools pip wheel failed with error code -5

### ISSUE THREAD

**Issue by enriqueromualdez** [mhallsmoore/qstrader#204]
I'm having difficulty with the virtual env: virtualenv --no-site-packages -p python3 .

Here's the error:

Enriques-MacBook-Air:qstraderp3 enriqueromualdez$ virtualenv --no-site-packages -p python3 .
Running virtualenv with interpreter /anaconda/bin/python3
Using base prefix '/anaconda'
New python executable in /Users/enriqueromualdez/venv/qstraderp3/bin/python3
Not overwriting existing python script /Users/enriqueromualdez/venv/qstraderp3/bin/python (you must use /Users/enriqueromualdez/venv/qstraderp3/bin/python3)
dyld: Library not loaded: @rpath/libpython3.6m.dylib
  Referenced from: /Users/enriqueromualdez/venv/qstraderp3/bin/python3
  Reason: image not found
Installing setuptools, pip, wheel...
  Complete output from command /Users/enriqueromual...traderp3/bin/python3 - setuptools pip wheel:
  dyld: Library not loaded: @rpath/libpython3.6m.dylib
  Referenced from: /Users/enriqueromualdez/venv/qstraderp3/bin/python3
  Reason: image not found
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/virtualenv.py", line 945, in create_environment
    download=download,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/enriqueromual...traderp3/bin/python3 - setuptools pip wheel failed with error code -5

The initial installation failed, so I reinstalled anaconda, deleted exiting virtualenv, but now I can't seem to get past this step..

Thank you!

**Comment by enriqueromualdez** [comment]
Hello all, 

I managed to solve this issue by conda installing virtualenv and updating anaconda. 
It turns out virtualenv was not automatically installed with Anaconda.
