### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'not_empty'

### ISSUE THREAD

**Issue by cqiaoYc** [mhallsmoore/qstrader#209]
My python version is 3.6. When I ran intraday_ml_backtest.py, got:
==================
Running Backtest...
Traceback (most recent call last):
  File "D:/python_study/AdvancedAlgorithmicTrading/intraday_ml_backtest.py", line 108, in <module>
    main()
  File "D:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "D:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "D:/python_study/AdvancedAlgorithmicTrading/intraday_ml_backtest.py", line 105, in main
    run(config, testing, tickers, filename)
  File "D:/python_study/AdvancedAlgorithmicTrading/intraday_ml_backtest.py", line 77, in run
    results = backtest.start_trading(testing=testing)
  File "D:\ProgramData\Anaconda3\lib\site-packages\qstrader\trading_session.py", line 156, in start_trading
    self._run_session()
  File "D:\ProgramData\Anaconda3\lib\site-packages\qstrader\trading_session.py", line 123, in _run_session
    event = self.events_queue.get(False)
  File "D:\ProgramData\Anaconda3\lib\queue.py", line 158, in get
    with self.not_empty:
AttributeError: 'bool' object has no attribute 'not_empty'
================
What's wrong? Python libs version?

**Comment by enriqueromualdez** [comment]
Hi @cqiaoYc,

Not sure if this will help, but I did run into issues when I ran this with Python 3.6. I was recommended to use an older Anaconda Distribution (I used 4.2) to downgrade my Python version to 3.5. All issues were solved after that.

Hope this helps!

**Comment by cqiaoYc** [comment]
@enriqueromualdez,
 thank you!

**Comment by enriqueromualdez** [comment]
@cqiaoYc You're welcome! If the fix worked, would you mind closing this issue as well? Thanks!

**Comment by cqiaoYc** [comment]
I switched to Python3 5, but the trouble still exists.

**Comment by enriqueromualdez** [comment]
Hi @cqiaoYc ,

I think this may have something to do with the format of the intraday_ml_backtest.py file. Has it been configured to run on existing build of QSTrader?

**Comment by cqiaoYc** [comment]
SQTrader was installed by pip.

**Comment by cqiaoYc** [comment]
conf in main():
     testing=False
    config=settings.DEFAULT_CONFIG_FILENAME
    config = settings.from_file(config, testing)
    # config=SettingsDefault()
    run(config, testing, tickers, filename)
===============

**Comment by chillliang** [comment]
@cqiaoYc  I'm having a similar 'no attribute' problem with the .py files (#220). I was wondering if you've found any resolution to this yet?
