### ISSUE TITLE
couldn't run buy_and_hold example on win10 with' No such file or directory: 'C:\\SPB_Data/out\\tradelog_2017-08-31.csv'

### ISSUE THREAD

**Issue by fredwang222** [mhallsmoore/qstrader#225]
Hi,
   I tried to install qstrader and run example on win10 (Anaconda3 installed) but failed. 
The installation step is placed the qstrader in Anaconda Lib\site_packages and run installation. I created data(copy the data there) and out dirs. When I tried to install example, the error is as following. Could u pls helpl? Thanks in advance.

- Fred

Traceback (most recent call last):
  File "buy_and_hold_backtest.py", line 70, in <module>
    run(config, testing, tickers, filename)
  File "buy_and_hold_backtest.py", line 56, in run
    events_queue, title=title
  File "C:\Users\wangyuanhong\Anaconda3\lib\site-packages\qstrader-0.0.1-py3.5.egg\qstrader\trading_session.py", line 52, in __init__
  File "C:\Users\wangyuanhong\Anaconda3\lib\site-packages\qstrader-0.0.1-py3.5.egg\qstrader\trading_session.py", line 87, in _config_session
  File "C:\Users\wangyuanhong\Anaconda3\lib\site-packages\qstrader-0.0.1-py3.5.egg\qstrader\compliance\example.py", line 43, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\SPB_Data/out\\tradelog_2017-08-31.csv'

**Comment by fredwang222** [comment]
have found the reason
