### ISSUE TITLE
Problem installing QSTrader

### ISSUE THREAD

**Issue by dmorgan75** [mhallsmoore/qstrader#227]
After I enter the command: pip install git+https://github.com/mhallsmoore/qstrader.git, the following exception is displayed after various packages have been collected and after an installing message is displayed:

Exception:
Traceback (most recent call last):
  File "/home/david/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/david/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/david/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/david/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/david/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/david/.local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/david/.local/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/home/david/.local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pytz-2017.2.dist-info'

If I then enter the command: pip install -r https://raw.githubusercontent.com/mhallsmoore/, the following exception is displayed:

Exception:
Traceback (most recent call last):
  File "/home/david/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/david/.local/lib/python2.7/site-packages/pip/commands/install.py", line 312, in run
    wheel_cache
  File "/home/david/.local/lib/python2.7/site-packages/pip/basecommand.py", line 295, in populate_requirement_set
    wheel_cache=wheel_cache):
  File "/home/david/.local/lib/python2.7/site-packages/pip/req/req_file.py", line 84, in parse_requirements
    filename, comes_from=comes_from, session=session
  File "/home/david/.local/lib/python2.7/site-packages/pip/download.py", line 418, in get_file_content
    resp.raise_for_status()
  File "/home/david/.local/lib/python2.7/site-packages/pip/_vendor/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 400 Client Error: Bad Request for url: https://raw.githubusercontent.com/mhallsmoore/

I'm using Ubuntu 16.04.3.

I followed  the "How to setup Ubuntu Linux from scratch to install and run QSTrader" instructions to the letter. The first problem I encountered was with the virtualenv --no-site-packages -p python3 bin/activate command. The problem was that virtualenv was not installed, so I used the command provided by Terminal to install it. This fixed the problem.

When I initially tried to run the next command in the installation process (i.e. pip install git+https://github.com/mhallsmoore/qstrader.git), I received an error message that pip was not installed. I fixed this error by using the command provided by Terminal to install it. I then received an error message that git was not installed, so I installed it using the command provided by Terminal.

I don't know how to proceed with the exceptions mentioned above.

**Comment by JamesKBowler** [comment]
The commands are:

pip install git+https://github.com/mhallsmoore/qstrader.git
pip install -r https://raw.githubusercontent.com/mhallsmoore/qstrader/master/requirements.txt

Your executing.
pip install -r https://raw.githubusercontent.com/mhallsmoore/

**Comment by JamesKBowler** [comment]
any luck?

**Comment by dmorgan75** [comment]
Thanks, James. (My apologies for my late reply - I've been really busy with other things the last month or so.)

I have yet to try the commands you posted above. I'll let you know what happens once I do.

Thanks again.
