### ISSUE TITLE
Running Example Buy and Hold using custom data

### ISSUE THREAD

**Issue by tanaytrivedi** [mhallsmoore/qstrader#239]
Hello,
I tried using the buy_and_hold strategy on my own custom data but it produces and error. I'm running on Mac OSX using Anaconda. The example strategy works fine when I have the ticker set to:
`ticker=['SPY']`, but when I run on my own data (in this case one year of daily prices of Ethereum) I get the following traceback:
```Running Backtest...
Traceback (most recent call last):
  File "buy_and_hold_backtest.py", line 70, in <module>
    run(config, testing, tickers, filename)
  File "buy_and_hold_backtest.py", line 58, in run
    results = backtest.start_trading(testing=testing)
  File "/anaconda/envs/qstrader/lib/python3.4/site-packages/qstrader/trading_session.py", line 157, in start_trading
    results = self.statistics.get_results()
  File "/anaconda/envs/qstrader/lib/python3.4/site-packages/qstrader/statistics/tearsheet.py", line 85, in get_results
    dd_s, max_dd, dd_dur = perf.create_drawdowns(cum_returns_s)
  File "/anaconda/envs/qstrader/lib/python3.4/site-packages/qstrader/statistics/performance.py", line 93, in create_drawdowns
    perf["Drawdown"].ix[0] = 0.0
  File "/anaconda/envs/qstrader/lib/python3.4/site-packages/pandas/core/indexing.py", line 140, in __setitem__
    indexer = self._get_setitem_indexer(key)
  File "/anaconda/envs/qstrader/lib/python3.4/site-packages/pandas/core/indexing.py", line 127, in _get_setitem_indexer
    return self._convert_to_indexer(key, is_setter=True)
  File "/anaconda/envs/qstrader/lib/python3.4/site-packages/pandas/core/indexing.py", line 1177, in _convert_to_indexer
    raise ValueError("cannot set by positional indexing with "
ValueError: cannot set by positional indexing with enlargement
```
I have put the file called `ETH.csv` in my `~/data` folder, which is where the YAML file point to look for. 

Not sure what else I need to do for this to work. This wasn't explicitly covered elsewhere so I decided posting this issue would not only be helpful for me but for quick help for someone else booting this up for the first time.
Thanks for the help!

**Comment by tanaytrivedi** [comment]
Relevant to this may be a view of what the data looks like:
```
Date,Open,High,Low,Close,Volume,Adj Close
2016-10-03,13.450724625898951,13.452120608331779,13.449874756022643,13.45127073845547,28.823554453573202,13.45127073845547
2016-10-04,13.452144675934441,13.455715625009026,13.44956736111875,13.453112962971165,23.193099934156226,13.453112962971165
2016-10-05,13.280144097229694,13.283521643523454,13.277739930563149,13.281037152782872,21.399428398625094,13.281037152782872
2016-10-06,12.953040162039054,12.955333912037812,12.951247453705832,12.953539004630514,24.083311633179598,12.953539004630514
2016-10-07,12.763339814807631,12.765425347215428,12.761050115733491,12.763125231474612,26.98566288330054,12.763125231474612
```
The columns seem to match the SPY.csv file. Any advice on how to format this so pandas doesn't complain about the indexing?

**Comment by dreamfrost** [comment]
Same question. I have installed it using Anaconda. But the example doesn't work with a traceback like "Could not subscribe ticker AAPL as no data CSV found for pricing." But I can see the AAPL in the file of  "~data".  No ideal where the data should be put.

**Comment by frankier234** [comment]
When configuring the strategy make sure you set the start_date and end_date to mirror the date range in your data file.

**Comment by tanaytrivedi** [comment]
@frankier234 excellent point, that made it work fine. Thanks for the help.
