### ISSUE TITLE
Error Installing and running example code

### ISSUE THREAD

**Issue by jiadingfang** [mhallsmoore/qstrader#240]
Hi,

I substitute the virtualenv part with anaconda, and follow the rest commands, however I get error running the example "buy_and_test_backtest.py" code. And here is my error message:

`python buy_and_hold_backtest.py
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "/home/jfang16/anaconda3/lib/python3.6/site-packages/pandas/__init__.py", line 25, in <module>
    from pandas import hashtable, tslib, lib
ImportError: numpy.core.multiarray failed to import

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "buy_and_hold_backtest.py", line 7, in <module>
    from qstrader.trading_session import TradingSession
  File "/home/jfang16/anaconda3/lib/python3.6/site-packages/qstrader/trading_session.py", line 5, in <module>
    from .price_handler.yahoo_daily_csv_bar import YahooDailyCsvBarPriceHandler
  File "/home/jfang16/anaconda3/lib/python3.6/site-packages/qstrader/price_handler/yahoo_daily_csv_bar.py", line 3, in <module>
    import pandas as pd
  File "/home/jfang16/anaconda3/lib/python3.6/site-packages/pandas/__init__.py", line 31, in <module>
    "extensions first.".format(module))
ImportError: C extension: umpy.core.multiarray failed to import not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.

After searching on the web, I find it is a numpy version collision problem, so I upgrade the numpy as follows
`pip install numpy --upgrade`

But now my error message becomes:

python buy_and_hold_backtest.py
Traceback (most recent call last):
  File "buy_and_hold_backtest.py", line 7, in <module>
    from qstrader.trading_session import TradingSession
  File "/home/jfang16/anaconda3/lib/python3.6/site-packages/qstrader/trading_session.py", line 12, in <module>
    from .statistics.tearsheet import TearsheetStatistics
  File "/home/jfang16/anaconda3/lib/python3.6/site-packages/qstrader/statistics/tearsheet.py", line 8, in <module>
    import qstrader.statistics.performance as perf
  File "/home/jfang16/anaconda3/lib/python3.6/site-packages/qstrader/statistics/performance.py", line 5, in <module>
    from scipy.stats import linregress
  File "/home/jfang16/anaconda3/lib/python3.6/site-packages/scipy/stats/__init__.py", line 338, in <module>
    from .stats import *
  File "/home/jfang16/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py", line 183, in <module>
    from . import distributions
  File "/home/jfang16/anaconda3/lib/python3.6/site-packages/scipy/stats/distributions.py", line 10, in <module>
    from ._distn_infrastructure import (entropy, rv_discrete, rv_continuous,
  File "/home/jfang16/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/jfang16/anaconda3/lib/python3.6/site-packages/scipy/optimize/__init__.py", line 233, in <module>
    from ._minimize import *
  File "/home/jfang16/anaconda3/lib/python3.6/site-packages/scipy/optimize/_minimize.py", line 30, in <module>
    from .lbfgsb import _minimize_lbfgsb
  File "/home/jfang16/anaconda3/lib/python3.6/site-packages/scipy/optimize/lbfgsb.py", line 44, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "/home/jfang16/anaconda3/lib/python3.6/site-packages/scipy/sparse/__init__.py", line 214, in <module>
    from .csr import *
  File "/home/jfang16/anaconda3/lib/python3.6/site-packages/scipy/sparse/csr.py", line 13, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
ImportError: /home/jfang16/anaconda3/lib/python3.6/site-packages/numexpr/../../../libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/jfang16/anaconda3/lib/python3.6/site-packages/scipy/sparse/_sparsetools.cpython-36m-x86_64-linux-gnu.so)

I ran it on a Linux 16.04 machine, and my teammates ran it on MAC, and they get similar error. Were you aware of this issues before? What are some possible solution?

Thanks,

**Comment by mhallsmoore** [comment]
Hi @kudo1026,

Did you manage to get it running on Ubuntu 16.04? If so, did you use the native Python 3.5 version or did you install Anaconda on your Linux box as well?

It looks to me that the correct version of GCC is not being linked to on your Mac.

Could you try the following command for me?

```conda install libgcc```

That might fix your problem.

Cheers,

Mike.

PS. Just to let you know that we're working on a brand new version of QSTrader that will be designed to work on Anaconda 3.5, 3.6 under Windows, Mac and Linux. If you view the README.md on QSTrader homepage, you can find out more about this version.
