### ISSUE TITLE
No module named 'qstrader.price_parser' ,for help

### ISSUE THREAD

**Issue by edwardhuanghz** [mhallsmoore/qstrader#381]
>>> from qstrader.price_parser import PriceParser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'qstrader.price_parser'
>>> 
>>> 
>>> import qstrader
>>> 

>>> from qstrader.event import (SignalEvent, EventType)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'qstrader.event'

**Comment by edwardhuanghz** [comment]
import qstrader is ok,
